CBO/Dej/urls.py
"""
urls module
"""
from django.urls import path

from Dej import views

app_name = 'Dej'
urlpatterns = [
    path('', views.IndexView.as_view(), name="home"),
    path("NewPetitDejView/", views.NewPetitDejView.as_view(), name="NewPetitDejView"),
    path('NewPetitDejViewVue/', views.NewPetitDejViewVue.as_view(), name="NewPetitDejViewVue"),

    path('PetitDej/add/', views.PetitDejCreate.as_view(), name='PetitDej-add'),
    path('PetitDej/<int:pk>/', views.PetitDejUpdate.as_view(), name='PetitDej-update'),
    path('PetitDej/<int:pk>/delete/', views.PetitDejDelete.as_view(), name='PetitDej-delete'),

    path('ListUserView/', views.ListUserView.as_view(), name="ListUserView"),
    path('UserDetailView/<str:email>', views.UserDetailView.as_view(), name="UserDetailView"),

]

CBO/DjangoSite/urls.py
# -*- coding: utf-8 -*-
"""DjangoSite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from Dej import views
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('Dej/', include('Dej.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

CBO/Dej/views.py
"""
views module
"""
# ================================================= Import des packages ================================================
# OS
import datetime
import functools
import json

# Data Vis
import bokeh
# Django
import django
from bokeh.resources import INLINE  # noqa
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.safestring import mark_safe
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

# Homemade packages
from Dej.models import PetitDej, PetitDejForm, User
from Dej.models import ResponsablePetitDej
from Dej.utils import Calendar


# ====================================== Variable init =================================================================
LOGIN_ = '/login/'
RESS2 = bokeh.resources.Resources('cdn')


# ====================================== Definition functions ==========================================================
@functools.lru_cache(maxsize=256)
def get_possible_labels_users(label):
    results = [x[label] for x in User.objects.order_by().values(label).distinct()]
    results = sorted(results, key=lambda x: x.lower())
    return results


def participate(user, petit_dej):
    return (user in petit_dej.organisateurs) or (user in petit_dej.participants)


def arg_is_yes(x):
    return x in ["true", "True", True, "y", "Y", "o", "Oui", "oui", "yes", "YES"]


# ====================================== Classes def   =================================================================
class IndexView(LoginRequiredMixin, TemplateView):
    login_url = LOGIN_
    redirect_field_name = 'redirect_to'
    template_name = "home.html"

    def __init__(self, *args, **kwargs):
        super(TemplateView, self).__init__(*args, **kwargs)
        self.context = {}

    def get(self, request, *args, **kwargs):
        self.context["csrf_token"] = django.middleware.csrf.get_token(request)
        return render(request, 'home.html', {})


class PetitDejCreate(CreateView):
    model = PetitDej
    form_class = PetitDejForm
    template_name = "PetitDejCreate.html"


class PetitDejUpdate(UpdateView):
    model = PetitDej
    form_class = PetitDejForm
    template_name = "PetitDejUpdate.html"


class PetitDejDelete(DeleteView):
    model = PetitDej
    success_url = reverse_lazy('author-list')
    form_class = PetitDejForm
    template_name = "PetitDejDelete.html"


class ListUserView(LoginRequiredMixin, ListView):
    login_url = LOGIN_
    redirect_field_name = 'redirect_to'
    template_name = "UserList.html"
    model = User
    context_object_name = 'users'  # Default: object_list
    paginate_by = 200
    queryset = User.objects.all().order_by("-nombre_points")  # Default: Model.objects.all()

    def get_queryset(self):
        """Return the last five published questions."""
        queryset = self.queryset

        equipe_filter = self.request.GET.get("equipe_filter", None)

        if isinstance(equipe_filter, str) and (len(equipe_filter) == 0):
            equipe_filter = None

        return queryset.order_by('-nombre_points')

    def get_context_data(self, **kwargs):
        context = super(ListUserView, self).get_context_data(**kwargs)
        context["all_equipes"] = get_possible_labels_users("equipe")
        return context


class UserDetailView(LoginRequiredMixin, TemplateView):
    login_url = LOGIN_
    redirect_field_name = 'redirect_to'
    template_name = "UserDetailView.html"

    def get(self, request, email=None, *args, **kwargs):
        user = User.objects.get(email=email)
        petit_dejs = PetitDej.objects.all()
        all_points = [round(petit_dej.points().get(user.email, 0), 2) for petit_dej in petit_dejs]
        petit_dejs = [petit_dej.to_dict(point=point) for petit_dej, point in zip(petit_dejs, all_points)]
        return render(request, self.template_name, {"user": user,
                                                    "petit_dejs": petit_dejs})


class NewPetitDejView(TemplateView, LoginRequiredMixin):
    login_url = LOGIN_
    redirect_field_name = 'redirect_to'
    template_name = "PetitDejNew.html"

    def __init__(self, *args, **kwargs):
        self.context = {"css_files": RESS2.css_files,
                        "js_files": RESS2.js_files,
                        "bokeh_scripts": []}
        self.init_context()
        super(NewPetitDejView, self).__init__(*args, **kwargs)

    def init_context(self):
        today = datetime.date.today()
        cal = Calendar(today.year, today.month)
        html_cal = cal.formatmonth(theyear=None, themonth=None, withyear=True)
        self.context["calendar"] = mark_safe(html_cal)  # nosec

    def get(self, request, *args, **kwargs):
        self.context["csrf_token"] = django.middleware.csrf.get_token(request)
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        self.context["csrf_token"] = django.middleware.csrf.get_token(request)
        return self.get(request, *args, **kwargs)


class NewPetitDejViewVue(TemplateView):

    def post(self, request):
        data = {}

        # Recuperation et cleaning des parametres
        date = request.POST.get("date")
        if date is None or len(date) == 0:
            date = datetime.datetime.now()
        if isinstance(date, str):
            date = datetime.datetime.strptime(date, '%Y-%m-%dT%H:%M:%S.%f')

        data["date"] = date.strftime('%Y-%m-%dT%H:%M:%S.%f')

        add_organisateur = arg_is_yes(request.POST.get("add_organisateur", False))
        add_designated_orga = arg_is_yes(request.POST.get("add_designated_orga", False))
        save = arg_is_yes(request.POST.get("save", False))

        # Mise à jour du petit dejeuner
        if "top_init" in request.POST:
            petit_dej = PetitDej(date=datetime.datetime.today())
            petit_dej.save()
        else:
            uri = request.POST["uri"]

            petit_dej = PetitDej.objects.get(uri=uri)
            petit_dej.date = date
            petit_dej.participation_validation = arg_is_yes(request.POST.get("participation_vali"))
            petit_dej.save()

            # Ajout des absents
            petit_dej.absents.clear()
            absents = User.objects.filter(email__in=json.loads(request.POST.get("absent_emails")))
            absents_email = [x.email for x in absents]
            petit_dej.absents.add(*list(absents))

            # Ajout des respos
            petit_dej.respos.all().delete()
            organisateurs = json.loads(request.POST.get("organisateurs"))
            organisateurs = [x for x in organisateurs if not x["delete"]]
            organisateurs = [x for x in organisateurs if (x["responsable"]["email"] not in absents_email)]

            for organisateur in organisateurs:
                responsable = ResponsablePetitDej(
                    responsable=User.objects.get(email=organisateur["responsable"]["email"]),
                    petit_dej=petit_dej,
                    fait_maison=organisateur["fait_maison"])
                responsable.save()

            # Ajout d'un nouvel organisateur
            if add_organisateur:
                petit_dej.tirage_aleatoire()
                data["add_organisateur"] = True

            if add_designated_orga:
                designated_orgna = request.POST["designated_orgna"]

                respo = ResponsablePetitDej(responsable=User.objects.get(email=designated_orgna),
                                            petit_dej=petit_dej,
                                            fait_maison=False)
                respo.save()
                data["add_designated_orga"] = True

            if save:
                petit_dej.send_mail()

        data["organisateurs"] = [x.to_dict() for x in petit_dej.respos.all()]
        data["absents"] = [x.email for x in petit_dej.absents.all()]
        data["possible_users"] = [user.to_dict() for user in petit_dej.possible_users]
        data["uri"] = petit_dej.uri

        return JsonResponse(data)

CBO/Dej/templates/PetitDejCreate.html
{% extends "base_site.html" %}
{% load static %}

{% block content %}

<div >
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
</div>

{% endblock %}

CBO/Dej/templates/PetitDejNew.html
{% extends "base_site.html" %}
{% load widget_tweaks %}
{% load static %}

{% block head %}
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://unpkg.com/vue-select@latest"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">

    {% for item in css_files%}
        <link href="{{ item }}" rel="stylesheet" type="text/css">
        {% endfor %}
        {% for item in js_files%}
        <script src="{{ item }}"></script>
        {% endfor %}
        {% for script in bokeh_scripts %}
        {{ script | safe }}
    {% endfor %}

{% endblock %}


{% block subtitle %}
    <p>Bonjour <span class="username"> {{ user.first_name }} </span> !</p>
{% endblock %}

{% block content %}
<h2> Bienvenue sur l'application CBO !</h2>

    <div>{{ calendar }}</div>

    <div id="app">
        <div>
            <label>Date du petit déjeuner</label>
            <input type="datetime" name="date" v-model="date"/>
        </div>

        <div>
            <label>Participation de la validation ?</label>
            <input type="checkbox" v-model="participation_vali" @change="load_data()">
        </div>
        <div>
            <label>Nombre de participants : ##nb_participants##</label>
        </div>

        <h3>Les absents</h3>
        <div>
            <select v-model="absent_emails" multiple>
                <option v-for="user in possible_users">##user.email##</option>
            </select>
        </div>
        <br>

        <h3>Les organisateurs</h3>
        <div v-for="organisateur in organisateurs">
            <label>Responsable</label>
            <label style="font-weight: bold">##organisateur.responsable.email##</label>
            <label>Fait maison?</label>
            <input type="checkbox" v-model="organisateur.fait_maison">
            <label>Delete</label>
            <input type="checkbox" v-model="organisateur.delete" @change="load_data()">
        </div>
        <a class="my_button" @click="add_organisateur_func()">Ajouter un organisateur</a>
        <a class="my_button" @click="save_data()">Enregistrer</a>
        <div>
            <label>Organisateur désigné</label>
            <select v-model="designated_orgna"
                    @change="add_designated_orga_func()">
                <option v-for="user in possible_users">##user.email##</option>
            </select>
        </div>
    </div>


    <script>
        var app = new Vue({
        el: '#app',
        delimiters: ['##', '##'],
        data: {"date": "",
                "participation_vali": true,
                "organisateurs": [],

                "add_organisateur": false,
                "add_designated_orga": false,

                "possible_users": [],
                "absent_emails": [],
                "save": false,
                "uri": "",
                "designated_orgna": "",
               } ,

        computed: {
            nb_participants: function () {
                  return this.possible_users.length - this.absent_emails.length
                },
            },

        methods: {
            add_organisateur_func(){
                this.add_organisateur = true
                this.load_data()
                this.add_organisateur = false
            },
            add_designated_orga_func(){
                this.add_designated_orga = true
                this.load_data()
                this.add_designated_orga = false
            },

            save_data(){
                this.save = true
                this.load_data()
                this.save = false
            },

            init(){
                var self = this;
                $.ajax({
                   url: '{% url 'Dej:NewPetitDejViewVue' %}',
                   data : {"top_init": true,
                          'csrfmiddlewaretoken': '{{ csrf_token }}',
                   },
                   method: "POST",
                   success: function(data) {
                        self.uri = data.uri
                        self.date = data.date
                        self.organisateurs = data.organisateurs
                        self.possible_users = data.possible_users
                   },
                   error: function(error) {
                        console.log(error);
                   }
                })
            },

            load_data(){
                var self = this;

                data = {'date': this.date,
                           'uri': this.uri,
                           'csrfmiddlewaretoken': '{{ csrf_token }}',
                           'participation_vali': this.participation_vali,
                           "organisateurs": JSON.stringify(this.organisateurs),
                           "absent_emails": JSON.stringify(this.absent_emails),
                           "add_organisateur": this.add_organisateur,
                           "add_designated_orga": this.add_designated_orga,
                           "save": this.save}

                if (this.designated_orgna){
                    data["designated_orgna"] = this.designated_orgna

                }
                $.ajax({
                    url: '{% url 'Dej:NewPetitDejViewVue' %}',
                    data: data,

                    method: 'POST',
                    success: function(data) {
                        self.date = data.date
                        self.organisateurs = data.organisateurs
                        self.possible_users = data.possible_users

                        if (data.add_designated_orga){
                            self.designated_orgna = ""
                        }
                        },
                    error: function(error) {
                        console.log(error);
                        }
                    });
            },
        },
        mounted: function() {
            this.init()}
        })

    </script>
{% endblock %}

CBO/Dej/templates/PetitDejUpdate.html
{% extends "base_site.html" %}
{% load static %}

{% block content %}

<div >
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
</div>

{% endblock %}

CBO/Dej/templates/UserDetailView.html
{% extends "base_site.html" %}
{% load static %}

{% block head %}
<style>
    table{
        border: 1px;
        padding: 3px;
        border-spacing: 0px;
    }
    tr{
        border: 1px solid black;
        text-align: center
    }
    tr.ligne-impaire{
        background-color: rgb(0, 106, 77);
        color : white
    }
    tr.ligne-paire{
        background-color: rgb(240, 247, 240);
    }
    tr.ligne-paire:hover{
        background-color: rgb(163, 204, 193)
    }
</style>
{% endblock %}

{% block content %}
<div>
    <h4>{{user.username}}</h4>
    <ul>
        <li>Email: {{user.email}}</li>
        <li>Arrivée: {{user.date}}</li>
        <li>Equipe : {{user.equipe}}</li>
        <li>Points : {{user.nombre_points}}</li>
    </ul>


    <div style="margin-top: 70px;">
        <h4>Petits déjeuners</h4>
        <table aria-describedby="Tableau des déjeuners" class="table table-bordered">
            <th scope="col" class="ligne-impaire">
                <td>Date</td>
                <td>Vali?</td>
                <td>Absents</td>
                <td>Participants</td>
                <td>Organisateurs</td>
                <td>Mes points</td>
            </th>
            <tr>
            </tr>
            {% for petit_dej in petit_dejs %}
            <tr>
                <td><a href="/admin/Dej/petitdej/{{petit_dej.pk}}/change/">{{petit_dej.date}}</a></td>
                <td>{{petit_dej.participation_validation}}</td>
                <td>{{petit_dej.nombre_absents}}</td>
                <td>{{petit_dej.nombre_participants}}</td>
                <td>{{petit_dej.nombre_organisateurs}}</td>
                <td>{{petit_dej.point}}</td>
            </tr>
            {% endfor %}
        </table>

        {% if is_paginated %}
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
              <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="active" style="margin-left:5px"><span> {{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li style="margin-left:5px"><a href="?page={{ i }}">  {{ i }}  </a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
          </ul>
        {% endif %}

    </div>


</div>


{% endblock %}

CBO/Dej/templates/UserList.html
{% extends "base_site.html" %}
{% load static %}

{% block head %}
<style>
    table {
        border: 1px;
        padding: 3px;
        border-spacing: 0px;
    }
    tr {
        border: 1px solid black;
        text-align: center
    }
    tr.ligne-impaire{
        background-color: rgb(0, 106, 77);
        color : white
    }
    tr.ligne-paire{
        background-color: rgb(240, 247, 240);
    }
    tr.ligne-paire:hover{
        background-color: rgb(163, 204, 193)
    }
</style>
{% endblock %}

{% block content %}

<div>

    <div style="flex-grow: 1; margin-top: 70px;">
        <h4>Filtres</h4>
        <form method="get" action="{% url 'Dej:ListUserView' %}">
            <label style="margin-top: 20px">Equipe</label>

            <select name="equipe_filter">
                <option value="">--Please choose an option--</option>
                {% for equipe in all_equipes %}
                    <option>{{ equipe }}</option>
                {% endfor %}
            </select>

            <input type="submit" name="Filtrer" value="Filtrer"/></p>
        </form>
    </div>

    <div style="margin-top: 70px;">
        <h4>Utilisateurs</h4>
        <table aria-describedby="Tableau des points" class="table table-bordered">
           <tr>
                <th scope="col">Email</th>
                <th scope="col">Prénom</th>
                <th scope="col">Equipe</th>
                <th scope="col">Points</th>
            </tr>
            {% for user in users %}
            <tr>
                <td><a href="{% url 'Dej:UserDetailView' user.email %}">{{ user.email }}</a></td>
                <td>{{user.username}}</td>
                <td>{{user.equipe}}</td>
                <td>{{user.nombre_points}}</td>
            </tr>
            {% endfor %}
        </table>

        {% if is_paginated %}
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
              <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="active" style="margin-left:5px"><span> {{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li style="margin-left:5px"><a href="?page={{ i }}">  {{ i }}  </a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
          </ul>
        {% endif %}

    </div>

</div>




{% endblock %}

CBO/Dej/templates/base_site.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
    <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/my_collapsible.css' %}" />
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>

    <style>
    /* The switch - the box around the slider */
    .switch {
    position: relative;
    display: inline-block;
    width: 60px;
    height: 34px;
    }

    /* Hide default HTML checkbox */
    .switch input {
    opacity: 0;
    width: 0;
    height: 0;
    }

    /* The slider */
    .slider {
    position: absolute;
    cursor: pointer;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: #ccc;
    -webkit-transition: .4s;
    transition: .4s;
    }

    .slider:before {
    position: absolute;
    content: "";
    height: 26px;
    width: 26px;
    left: 4px;
    bottom: 4px;
    background-color: white;
    -webkit-transition: .4s;
    transition: .4s;
    }

    input:checked + .slider {
    background-color: #006A4E;
    }

    input:focus + .slider {
    box-shadow: 0 0 1px #2196F3;
    }

    input:checked + .slider:before {
    -webkit-transform: translateX(26px);
    -ms-transform: translateX(26px);
    transform: translateX(26px);
    }

    /* Rounded sliders */
    .slider.round {
    border-radius: 34px;
    }

    .slider.round:before {
    border-radius: 50%;
    }

    </style>
    <style>
       label {
           color: #555;
           display: inline-block;
           margin-left: 18px;
           padding-top: 0px;
           font-size: 14px;
       }

      input {
           font-family: "Helvetica Neue", Helvetica, sans-serif;
           font-size: 12px;
           outline: none;
       }
       input[type=checkbox] {
           margin-left: 20px;
           margin-top: 0px;
       }


       .my_button {
            font: bold 11px Arial;
            text-decoration: none;
            background-color: #EEEEEE;
            color: #333333;
            padding: 2px 6px 2px 6px;
            border-top: 1px solid #CCCCCC;
            border-right: 1px solid #333333;
            border-bottom: 1px solid #333333;
            border-left: 1px solid #CCCCCC;
            border-radius: 30px;
            float: center;
            box-shadow: 0 1px 2px rgba(0, 0, 0, .3), inset 0 1px 0 rgba(255, 255, 255, .5);
            cursor: pointer;
       }
       .my_button:hover {
           background-image: -webkit-gradient(linear, left top, left bottom, from(#b6e2ff), to(#6ec2e8));
           background-image: -moz-linear-gradient(top left 90deg, #b6e2ff 0%, #6ec2e8 100%);
           background-image: linear-gradient(top left 90deg, #b6e2ff 0%, #6ec2e8 100%);
       }
       .my_button:active {
           background-image: -webkit-gradient(linear, left top, left bottom, from(#6ec2e8), to(#b6e2ff));
           background-image: -moz-linear-gradient(top left 90deg, #6ec2e8 0%, #b6e2ff 100%);
           background-image: linear-gradient(top left 90deg, #6ec2e8 0%, #b6e2ff 100%);
       }

    }
    </style>

    {% block head %}
    {% endblock %}
    {% block name %}
        <title>
            Petit déj, by CBO
        </title>
    {% endblock %}
    </head>
    <body>
        <div class="background">
            <header>
                <div class="titles">
                    <div class="title">
                        {% load static %}
                        <p> <a href="https://www.credit-agricole.com/"><img src="{% static 'gca.png' %}" alt="gca" height="100px"/></a>   </p>

                        <p class="blank"> ~~ </p>
                        <h1> {% block title %} Petit déj, by CBO.{% endblock %}</h1>
                    </div>
                    <p class="subtitle">
                        {% block subtitle %}
                        {% endblock %}
                    </p>
                </div>

                <div class="user">
                    {% if user.is_authenticated %}
                    <p> Connecté en tant que <span class="username"> {{ user.username }} </span> </p>
                    <p class="sep"> • </p>
                 
                    <a href="{% url 'logout'%}">
                        <p> Se déconnecter </p>
                    </a>
                    {% else %}
                        <a href="{% url 'login'%}">
                            <p> Se connecter </p>
                        </a>
                    {% endif %}
                </div>
            </header>
        
            <div class="tabs">
                {% block tabs %}
                <div class="foot_element">
                    <p>
                        <a href="{% url 'home' %}">
                            Accueil
                        </a>
                        <a class="clair" href="{% url 'Dej:ListUserView' %}">
                            Users
                        </a>

                        <a class="clair" href="{% url 'Dej:NewPetitDejView' %}">
                            Nouveau Petit-Dej
                        </a>
                        <a class="clair" href="{% url 'admin:index' %}">
                            Administrateur
                        </a>
                    </p>
                </div>
                {% endblock %}
            </div>

            <div id="main">
                {% block content %}
                <div class="part">
                    <h2> Content </h2>
                    <p> Your text here </p>
                </div>
                {% endblock %}
            </div>

            <footer>
                {% block footer %}
                <div class="foot_element">
                    <h5> Contact </h5>
                    <p> <a class="clair" href="mailto:Groupe-recherche-operationnelle.GRO@credit-agricole-sa.fr">GROrporate</a> </p>
                </div>
                <div class="foot_element">
                    <h5> About </h5>
                    <p> Website Django/CSS3/HTML5 </p>
                </div>
                {% endblock %}
            </footer>
        </div>
    </body>
</html>

CBO/Dej/templates/home.html
{% extends "base_site.html" %}
{% load static %}

{% block subtitle %}
    <p> Bonjour <span class="username"> {{ user.first_name }} </span> !</p>
{% endblock %}

{% block content %}
    <h2> Bienvenue sur l'application CBO du GRO !</h2>

{% endblock %}

CBO/Dej/templates/login.html
{% extends "base_site.html" %}
{% load static %}


{% block name %}
    <title>Connexion</title>
{% endblock %}

{% block title %}
    Connexion
{% endblock %}

{% block content %}

    {% if form.errors %}
        {{ form.errors }}
    {% endif %}

    {% if next %}
        {% if user.is_authenticated %}
        <p>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>
        {% else %}
        <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}

    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <table aria-describedby="Login">
        <tr style="background-color:#f8f9fa00;">
            <th id="tag">{{ form.username.label_tag }}</th>
            <th id="username">{{ form.username }}</th>
        </tr>
        <tr style="background-color:#f8f9fa00;">
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
        </table>

        <input type="submit" style="width:30%;" value="SE CONNECTER" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>


{% endblock %}